### PR TITLE
feat: add sounds on capture & check

### PR DESCRIPTION
**Pull request by t-trafer**
this PR closes issue #499

P.S: need suggestions to check piece capture - currently done based on last move text

### CODE REVIEW

**Comment by programarivm** [comment]
Thank you @t-trafer for this contribution.

Let me suggest the following:

- Rename `capture.mp3` as `move.mp3` and use this sound for moves including checks.
- Rename `check.mp3` as `capture.mp3` and use this sound for captures.

I can't wait to see what you come up with!

**Review by programarivm — CHANGES_REQUESTED** [review]
See https://github.com/chesslablab/react-chess/pull/644#issuecomment-1750155489

**Comment by t-trafer** [comment]
> Thank you @t-trafer for this contribution.
> 
> Let me suggest the following:
> 
> * Rename `capture.mp3` as `move.mp3` and use this sound for moves including checks.
> * Rename `check.mp3` as `capture.mp3` and use this sound for captures.
> 
> I can't wait to see what you come up with!

i can add another sound file for d

> Thank you @t-trafer for this contribution.
> 
> Let me suggest the following:
> 
> * Rename `capture.mp3` as `move.mp3` and use this sound for moves including checks.
> * Rename `check.mp3` as `capture.mp3` and use this sound for captures.
> 
> I can't wait to see what you come up with!

http://images.chesscomfiles.com/chess-themes/sounds/_MP3_/default/move-self.mp3 can use this for move sound if you'd so like..
we can have different move, capture, check sounds this way

**Comment by programarivm** [comment]
Excellent, thanks!

BTW, can the moves be taken from Lichess instead? I guess that would be the right thing to do in terms of copyright because Lichess is open source as well.

Keep it up,

**Comment by t-trafer** [comment]
@programarivm updated with lichess sound assets for move, capture & check - lmk what you think of it

**Comment by t-trafer** [comment]
> ```
> Failed to compile.
> 
> Module not found: Error: Can't resolve 'assets/mp3/Capture.mp3' in '/home/standard/projects/react-chess/src/features/sound'
> ERROR in ./src/features/sound/moveSounds.constants.js 3:0-50
> Module not found: Error: Can't resolve 'assets/mp3/Capture.mp3' in '/home/standard/projects/react-chess/src/features/sound'
> 
> ERROR in ./src/features/sound/moveSounds.constants.js 4:0-46
> Module not found: Error: Can't resolve 'assets/mp3/Check.mp3' in '/home/standard/projects/react-chess/src/features/sound'
> 
> webpack compiled with 2 errors
> ```

ah right.. git wouldn't recognise filename with case change only on case insensitive file system - file name change wasn't commiting.
Fixed it now, should be fine now

**Comment by programarivm** [comment]
Thanks for the updates!

Let me point out the following since ChesslaBlab PR branches are checked out from the `master` branch:

- Make sure to `git merge master` before pushing changes to a PR branch.

Happy learning,

**Comment by t-trafer** [comment]
> Thanks for the updates!
> 
> Let me point out the following since ChesslaBlab PR branches are checked out from the `master` branch:
> 
> * Make sure to `git merge master` before pushing changes to a PR branch.
> 
> Happy learning,

up to date

**Pull request merged**
