### PR TITLE
draft adaptive color scheme UI #688

### PR DESCRIPTION
**Pull request by d47081**
About issues 

#688 
#533

In this branch I have removed backgrounds and borders definition and add

```
:root {
  color-scheme: light dark;
}
```

It must be same as before for light environments, but for dark one, requires more adaptations.

For example, I can't find where inline styles added to the steps history table that makes texts invisible there:

Pasted image

### CODE REVIEW

**Comment by programarivm** [comment]
If I'm not very much mistaken this is a [theme](https://github.com/chesslablab/react-chess/blob/master/src/styles/theme.js) customization.

**Comment by programarivm** [comment]
Also the light and dark mode theme toggle should be available in the **Settings** menu.

**Comment by programarivm** [comment]
Sorry about that, it is not available yet. The light and dark mode theme toggle needs to be implemented in the **Settings** menu.

**Comment by programarivm** [comment]
@dev0614 you may want to read this conversation before sending a PR.

Let's recap:

- A new MUI theme needs to be created.
- The light and dark mode theme toggle needs to be implemented in the **Settings** menu.

Also, the staging environment will soon be back to make things easier to frontend devs. The React Chess app will be able to query the staging chess server as well as the staging API.

At this moment, a full-stack environment needs to be set up.  

Keep it up,

**Comment by dev0614** [comment]
I got it.
I will add light mode and dark mode.

**Pull request closed without merging**
