### PR TITLE
Update Captcha.js making it not able to be copied

### PR DESCRIPTION
**Pull request by SmashedFrenzy16**
Fixes: https://github.com/chesslablab/react-chess/issues/627

### CODE REVIEW

**Review by programarivm — CHANGES_REQUESTED** [review]
I was just wondering if it'd be possible to convert the text to image without using jQuery.

**Comment by SmashedFrenzy16** [comment]
@programarivm I will try and look into it and attempt to add it.

**Comment by programarivm** [comment]
Thanks for the great work @SmashedFrenzy16,

We're one step away from closing pristine Hacktoberfest PRs! 

Let me suggest to focus on closing the following issues:

- https://github.com/chesslablab/chess-api/issues/112

Keep it up, and happy coding and learning.

**Comment by SmashedFrenzy16** [comment]
Ok @programarivm.

**Pull request closed without merging**
